[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

    [build]
  command = "bash install-rust.sh && pip install -r requirements.txt && python your_script.py"
  publish = "build"  # or your frontend build folder

[[plugins]]
  package = "@netlify/plugin-python"

[functions]
  directory = "netlify/functions"
